/* tslint:disable */
/* eslint-disable */
/**
 * NorthWind API
 * NorthWind Service API Documentation
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface NewOrderReqDTO
 */
export interface NewOrderReqDTO {

    /**
     * @type {string}
     * @memberof NewOrderReqDTO
     */
    customerID?: string | null;

    /**
     * @type {string}
     * @memberof NewOrderReqDTO
     */
    employeeID?: string | null;

    /**
     * @type {number}
     * @memberof NewOrderReqDTO
     */
    freight?: number;
}
