/* tslint:disable */
/* eslint-disable */
/**
 * NorthWind API
 * NorthWind Service API Documentation
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CustomerDto } from './customer-dto';
import { EmployeeDto } from './employee-dto';
import { ShipperDto } from './shipper-dto';
 /**
 * 
 *
 * @export
 * @interface OrderDropdownListsResponse
 */
export interface OrderDropdownListsResponse {

    /**
     * @type {Array<CustomerDto>}
     * @memberof OrderDropdownListsResponse
     */
    customers?: Array<CustomerDto> | null;

    /**
     * @type {Array<EmployeeDto>}
     * @memberof OrderDropdownListsResponse
     */
    employees?: Array<EmployeeDto> | null;

    /**
     * @type {Array<ShipperDto>}
     * @memberof OrderDropdownListsResponse
     */
    shippers?: Array<ShipperDto> | null;
}
