/* tslint:disable */
/* eslint-disable */
/**
 * NorthWind API
 * NorthWind Service API Documentation
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface QueryBasicOrderDTO
 */
export interface QueryBasicOrderDTO {

    /**
     * @type {number}
     * @memberof QueryBasicOrderDTO
     */
    orderId?: number;

    /**
     * @type {Date}
     * @memberof QueryBasicOrderDTO
     */
    orderDate?: Date | null;

    /**
     * @type {string}
     * @memberof QueryBasicOrderDTO
     */
    customerName?: string | null;

    /**
     * @type {number}
     * @memberof QueryBasicOrderDTO
     */
    freight?: number;

    /**
     * @type {Date}
     * @memberof QueryBasicOrderDTO
     */
    shippedDate?: Date | null;

    /**
     * @type {string}
     * @memberof QueryBasicOrderDTO
     */
    formattedFreight?: string | null;

    /**
     * @type {string}
     * @memberof QueryBasicOrderDTO
     */
    formattedOrderDate?: string | null;

    /**
     * @type {string}
     * @memberof QueryBasicOrderDTO
     */
    shipStatus?: string | null;
}
