/* tslint:disable */
/* eslint-disable */
/**
 * NorthWind API
 * NorthWind Service API Documentation
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ShipperDto
 */
export interface ShipperDto {

    /**
     * @type {string}
     * @memberof ShipperDto
     */
    id?: string | null;

    /**
     * @type {string}
     * @memberof ShipperDto
     */
    companyName?: string | null;
}
